# .github/workflows/doxygen.yml

name: Doxygen

on:
  push:
    branches:
      - master  # or 'main'
  pull_request:
    branches:
      - master # or 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
          submodules: true
    
    - name: Cache Doxygen and Graphviz
      id: cache-tools
      uses: actions/cache@v4
      with:
        path: /usr/local/doxygen_graphviz
        key: ${{ runner.os }}-doxygen-graphviz-1.8.17-2.43 # Change version numbers to match what you are using

    - name: Install Doxygen and Graphviz (if not in cache)
      if: steps.cache-tools.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz
        # Copy the installed binaries to a shared location for caching
        sudo mkdir -p /usr/local/doxygen_graphviz
        sudo cp /usr/bin/doxygen /usr/local/doxygen_graphviz/
        sudo cp /usr/bin/dot /usr/local/doxygen_graphviz/
        
    - name: Generate Doxygen Documentation
      run: doxygen Doxyfile
    
    - name: Copy Doxygen Awesome CSS
      run: cp -r ./doxygen-awesome-css/* ./docs/html/


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
        publish_branch: gh-pages
